# Generated by Django 5.2.6 on 2025-11-05 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='solicitud.gameimage', verbose_name='Juego'),
        ),
    ]
