# Generated by Django 5.2.6 on 2025-11-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='Nombre Clave')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Enlace')),
            ],
            options={
                'verbose_name': 'Red',
                'verbose_name_plural': 'Redes',
            },
        ),
    ]
