# Generated by Django 5.2.6 on 2025-12-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_juego_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='año',
            field=models.IntegerField(),
        ),
    ]
